# Generated by Django 4.1.5 on 2023-01-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_category'),
        ('news', '0004_auto_20200210_1243'),
    ]

    operations = [
    ]
